storefront_url: "https://www.euronics.co.uk/"
storefront_username: "mark.johnson@kps.com"
storefront_password: "Thinkpad1969!"
storefront_category_search: ""
storefront_product_search: ""
storefront_sku_search: ""
storefront_postcode: "BN10 7PU"
storefront_address: "21, Cairo Avenue"
storefront_home_phone: "01273 587646"
storefront_mobile_phone: "07935 259292"
storefront_card_name: "MR M C JOHNSON"
storefront_card_number: "4242424242424242"
storefront_card_expiry: "01/30"
storefront_card_cvv: "555"
members_url: "https://s.www.euronics.co.uk/members/"
members_username: "cihsupport9@cihgroup.com"
members_password: "Pass1234!"
backoffice_url: "https://s.admin.euronics.co.uk/backoffice/login.zul"
backoffice_username: "admin"
backoffice_password: "nimda"
hac_url: "https://s.admin.euronics.co.uk/hac/login"
hac_username: "admin"
hac_password: "nimda"
smartedit_url: "https://s.admin.euronics.co.uk/smartedit"
smartedit_username: "admin"
smartedit_password: "nimda"
